stages:
    - build
    - deploy

build:frontend:
    stage: build
    only:
      - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - docker-compose build frontend
        - docker-compose push frontend

build:backend:
    stage: build
    tags:
        - builder
    only:
      - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - docker-compose build backend
        - docker-compose push backend

deploy:environment:
    stage: deploy
    tags:
        - deploy
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    when: manual
    script:
        - docker-compose pull
        - docker-compose up -d