stages:
    - build
    - deploy

build:frontend:
    stage: build
    tags:
        - builder
    only:
      - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - docker-compose build frontend
        - docker-compose push frontend

build:backend:
    stage: build
    tags:
        - builder
    only:
      - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - docker-compose build backend
        - docker-compose push backend


deploy:environment:staging:
    stage: deploy
    tags:
        - deploy-staging
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    script:
        - docker-compose -f docker-compose-staging.yaml pull
        - docker-compose -f docker-compose-staging.yaml up -d

deploy:environment:production:
    stage: deploy
    tags:
        - deploy-production
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    when: manual
    script:
        - docker-compose pull
        - docker-compose up -d