version: "3.7"
services:
    backend:
        build:
            context: ./backend
        container_name: actionwidget_backend
        image: "jimber/actionwidget_backend:${CI_COMMIT_TAG}"
        restart: always
        # volumes:
        #     - todo
        networks:
            - actionwidget_network
    frontend:
        build:
            context: ./frontend
        container_name: actionwidget_frontend
        image: "jimber/actionwidget_frontend:${CI_COMMIT_TAG}"
        restart: always
        networks:
            - actionwidget_network
            - jimber_proxy_net
networks:
    actionwidget_network:
        jimber_proxy_net:
        external:
            name: jimber_proxy_net
volumes:
    database_volume:
